id: odoo_billing_1to1_flow
namespace: wonderbrands.finance.marketplaces
description: "Pipeline Facturación 1a1 Odoo: Generación de facturas individuales para el resto de canales (Producción)"

variables:
  repo_url: "https://github.com/wonderbrands/wb-data-hub.git"
  branch: "main"
  odoo_url: "https://somosreyes-test06072026-34522940.dev.odoo.com"
  odoo_db: "somosreyes-test06072026-34522940"

tasks:
  - id: working_env_1a1
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      
      - id: clone_repo
        type: io.kestra.plugin.git.Clone
        url: "{{ vars.repo_url }}"
        branch: "{{ vars.branch }}"
        username: "{{ secret('GIT_USER') }}"
        password: "{{ secret('GIT_TOKEN_WB') }}"

      - id: run_billing_1a1
        type: io.kestra.plugin.scripts.shell.Commands
        containerImage: wonderbrands-etl:v1
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
          pullPolicy: NEVER
        retry:
          type: constant
          interval: PT5M
          maxAttempt: 3
        env:
          odoo_urlV18: "{{ vars.odoo_url}}" 
          odoo_dbV18: "{{ vars.odoo_db}}"
          odoo_user_dataV18: "{{ secret('odoo_user_dataV18') }}"
          odoo_password_dataV18: "{{ secret('odoo_password_dataV18') }}"
        commands:
          - python processes/financial/billing_processes/general_invoice/facturacion_automatica_1a1.py

triggers:
  - id: hourly_schedule_15
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "15 * * * *" # Se ejecuta cada hora al minuto 15

errors:
  - id: slack_alert
    type: io.kestra.plugin.slack.notifications.SlackIncomingWebhook
    url: "{{ secret('SLACK_WEBHOOK') }}"
    payload: |
      {
        "text": "🚨 *¡Fallo en Pipeline de facturación general 1a1 (Odoo)!* 🚨\n*Flujo:* `{{ flow.id }}`\n*ID Ejecución:* `{{ execution.id }}`\n*Tarea Fallida:* `{{ execution.tasksRun | filter(t => t.state.current == 'FAILED') | map(t => t.taskId) | first }}`\n*Fecha:* `{{ execution.startDate }}`\n<http://<tu-url-de-kestra>/ui/executions/{{ flow.namespace }}/{{ flow.id }}/{{ execution.id }}|🔍 Ver logs completos en Kestra>"
      }