id: ml_daily_shipping_report
namespace: wonderbrands.shipping_labels.mercadolibre
description: "Genera reporte a demanda a partir de un Slash Command de Slack"

variables:
  repo_url: "https://github.com/wonderbrands/wb-data-hub.git"
  branch: "main"
  db_user: "kestra_bot"
  db_name: "tools"
  db1_host: "wonderbrands1.cuwd36ifbz5t.us-east-1.rds.amazonaws.com"

tasks:
  - id: working_dir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone_repo
        type: io.kestra.plugin.git.Clone
        url: "{{ vars.repo_url }}"
        branch: "{{ vars.branch }}"
        username: "{{ secret('GIT_USER') }}"
        password: "{{ secret('GIT_TOKEN_WB') }}"

      - id: generate_ondemand_csv
        type: io.kestra.plugin.scripts.shell.Commands
        containerImage: wonderbrands-python:v1
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
          pullPolicy: NEVER
        env:
          DB_HOST: "{{ vars.db1_host }}"
          DB_USER: "{{ vars.db_user }}"
          DB_PASSWORD: "{{ secret('DB_PASSWORD_KESTRA') }}"
          DB_NAME: "{{ vars.db_name }}"
          SLACK_BOT_TOKEN: "{{ secret('SLACK_BOT_TOKEN') }}"
          SLACK_CHANNEL_ID: "{{ secret('SLACK_CHANNEL_ID') }}"
        commands:
          #Texto que manda Slack
          - raw_body='{{ trigger.body }}'
          
          #  "&text="
          - text_encoded=$(echo "$raw_body" | awk -F'&text=' '{print $2}' | awk -F'&' '{print $1}')
          
          #Cambiar '+' por espacios
          - text_input=$(echo "$text_encoded" | tr '+' ' ')
          
          #Separar fechas para Python
          - fecha_inicio=$(echo $text_input | awk '{print $1}')
          - fecha_fin=$(echo $text_input | awk '{print $2}')
          
          # --- RUTA ---
          - python processes/wonderbrands/mercadolibre/ml_labels_report.py "$fecha_inicio" "$fecha_fin"
triggers:
  - id: slack_webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: "slack_reportes_wb_2026"