id: ml_api_flow
namespace: wonderbrands.mercadolibre.shipping_label
description: "Pipeline completo: Extrae de ML, clasifica SLA y prepara para Odoo"

# Variables globales
variables:
  repo_url:  "https://github.com/wonderbrands/wb-data-hub.git"
  branch: "main"
  odoo_url: "https://somosreyes.odoo.com"
  odoo_db: "wonderbrands2026-main-28990431"
  db_user: "kestra_bot"
  db_name: "tools"
  db1_host: "wonderbrands1.cuwd36ifbz5t.us-east-1.rds.amazonaws.com"

tasks:
  # WorkingDirectory garantiza que el Clone y el Python compartan los archivos
  - id: working_env_ml
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      
      # Clonar el repositorio
      - id: clone_repo
        type: io.kestra.plugin.git.Clone
        url: "{{ vars.repo_url }}"
        branch: "{{ vars.branch }}"
        # git keys
        username: "{{ secret('GIT_USER') }}"
        password: "{{ secret('GIT_TOKEN_WB') }}"

      - id: shipping_extractor_data_ml
        type: io.kestra.plugin.scripts.shell.Commands
        containerImage: wonderbrands-etl:v1
        #TaskRunnerejecuta en la imagen de Docker 
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
          pullPolicy: NEVER
        retry:
        # Reintentos: Si falla, espera 60 segundos, intenta 3 veces
          type: constant
          interval: PT1M
          maxAttempt: 3
        env:
          DB_HOST: "{{ vars.db1_host }}"
          DB_USER: "{{ vars.db_user }}"
          DB_PASSWORD: "{{ secret('DB_PASSWORD') }}"
          DB_NAME: "{{ vars.db_name }}"
        commands:
          # Ahora es un comando Shell puro, adiós SyntaxError
          - python marketplaces/mercadolibre/shipping_labels/ml_mix_db_api_sla_orders.py

      - id: shipping_inyector_labels_odoo_ml
        type: io.kestra.plugin.scripts.shell.Commands
        containerImage: wonderbrands-etl:v1
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
          pullPolicy: NEVER
        env:
          ODOO_URL: "{{ vars.odoo_url }}"
          ODOO_DB: "{{ vars.odoo_db }}"
          ODOO_USER: "{{ secret('odoo_user_dataV18') }}"
          ODOO_PASSWORD: "{{ secret('odoo_password_dataV18') }}"
          DB_HOST: "{{ vars.db1_host }}"
          DB_USER: "{{ vars.db_user }}"
          DB_PASSWORD: "{{ secret('DB_PASSWORD') }}"
          DB_NAME: "{{ vars.db_name }}"
        commands:
          - python marketplaces/mercadolibre/shipping_labels/ml_odoo_injection_labels.py

# Alertas en caso de fallo (Se ejecuta solo si las tareas anteriores fallan)
errors:
  - id: error_alerts
    type: io.kestra.plugin.core.log.Log 
    level: ERROR
    message: "¡ALERTA! El flujo de Mercado Libre ha fallado en la ejecución {{ execution.id }}. Revisa los logs."

#dispardor
triggers:
  - id: production_cron
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 * * * *" # Cada hora en minuto 0